In [2]:
import numpy as np

In [11]:
arr = np.array([[1,2,3],
       [4,5,6],
       [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Axis 0 (rows) → Operations move down the columns.
### Axis 1 (columns) → Operations move across the rows.

#### summing along the axes

In [12]:
print(np.sum(arr,axis=0))   #Sum along rows (down each column)

[12 15 18]


In [13]:
print(np.sum(arr,axis=1))   #Sum along columns (across each row)

[ 6 15 24]


## 2. Indexing in Multidimensional Arrays

In [15]:
print(arr[1, 2])   #accesing elements
#this prints: row = 1, column = 2

6


In [19]:
print(arr[0:2,1:3])
#this prints elements: row 0 and 1
#and from 0 and 1 row, access column 1 and 2

[[2 3]
 [5 6]]


## 3. Indexing in 3D Arrays

In [20]:
arr3D = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
    ])

In [21]:
print(arr3D.shape)

(2, 2, 3)


In [24]:
#accessing elements in 3D array
print(arr3D[0,1,2])
print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [26]:
print(arr[:,0])   # Get all rows of the first column

[1 4 7]


In [29]:
print(arr3D[:,0,:])   # Get the first row from each "sheet" in a 3D array

[[1 2 3]
 [7 8 9]]


In [31]:
arr[:, 1] = 0     #replacing all elements in column 1 by 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
